version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./docker
    restart: unless-stopped
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    networks:
      - app
    depends_on:
      - mysql
      - redis
  mysql:
    image: "mariadb:latest"
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - "./docker/data/db/:/var/lib/mysql"
    networks:
      - app
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - "./docker/data/redis/:/data"
    networks:
      - app
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]

networks:
  app:
    driver: bridge
