version: '3.8'
services:
  container:
    build:
      context: .
    restart: always
    tty: true
    ports:
      - '${APP_PORT-3000}:3000'

  elasticsearch:
    container_name: search-service-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    volumes:
      - ./docker/data/elastic:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "${FORWARD_ELASTIC_PORT-9200}:9200"
    restart: always

  pgsql:
    image: postgres:15.2
    ports:
      - '${FORWARD_DB_PORT-5432}:5432'
    volumes:
      - './docker/data/pgsql:/var/lib/postgresql/data'
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  redis:
    image: "redis:alpine"
    volumes:
      - "./docker/data/redis/:/data"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]

networks:
  default:
    name: tofisa-network
    external: true
